logging:
  level:
    root: info
    com.psc.sample: debug
server:
  port: 8086
#  error:
#    whitelabel:
#      enabled: false
spring:
  thymeleaf:
      cache: false
      prefix: classpath:/templates/
  aplication:
    name: oauth2
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-gennerator-mappings: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/oauth2?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: show6357
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 536851246325-qqeh57qjmd3mdrvf60osq0q30cb8gdkg.apps.googleusercontent.com
            client-secret: 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
            scope: email
          facebook:
            client-id: 574351927141622
            client-secret: 5de13680790e9f781337e3723e756b3f
            scope:
              - email
              - public_profile
          naver:
           client-id: QNVLhQWHiRZOoyWrzPia
           client-secret: gtS0fOc4Yh
           redirect-uri: http://localhost:8080/login/oauth2/code/naver
           authorization-grant-type: authorization_code
           scope: email
           client-name: Naver
          kakao:
            clientId: 079ee3884d6284a30d1da43a4a790267
            clientSecret: lQ55J4AZDNW1KAkfPFOgWnRhRhzrzKWG
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            redirectUri: "http://localhost:8080/login/oauth2/code/kakao"
            scope:
            - profile_nickname
            - profile_image
            - account_email
            clientName: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https:openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id
      
